/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package modulo.sistema.visao;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.ImageIcon;
import modulo.cadastro.visao.AtendenteBusca;

/**
 *
 * @author augusto
 */
public class SistemaVisao extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public SistemaVisao() 
    {
        initComponents();
        
        menu.add(Box.createRigidArea(new Dimension(100, 40)));
        
        submenuCadastros.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/cadastros.png")));
        submenuAtendente.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/atendente.png")));
        submenuCertificacao.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/certificacao.png")));
        submenuCliente.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/cliente.png")));
        submenuEspecializacao.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/especializacao.png")));
        submenuProfissional.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/profissional.png")));
        
        menuProcessos.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/processo.png")));
        submenuAgenda.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/agenda.png")));
        submenuAtendimento.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/atendimento.png")));
        submenuProntuario.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/prontuario.png")));
        
        menuConfiguracoes.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/configuracoes.png")));
        submenuPadraoDeAtendimento.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/padraoDeAtendimento.png")));
        submenuTipoDeAtendimento.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/tipoDeAtendimento.png")));
        submenuTipoDeProntuario.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/tipoDeProntuario.png")));
        
        menuAdministrativo.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/administrativo.png")));
        submenuLogout.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/logout.png")));
        submenuGrupoDeUsuarios.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/grupoDeUsuarios.png")));
        submenuUsuario.setIcon(new ImageIcon(this.getClass().getResource("/publico/imagens/usuario.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelConteudo = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        submenuCadastros = new javax.swing.JMenu();
        submenuAtendente = new javax.swing.JMenuItem();
        submenuCertificacao = new javax.swing.JMenuItem();
        submenuCliente = new javax.swing.JMenuItem();
        submenuEspecializacao = new javax.swing.JMenuItem();
        submenuProfissional = new javax.swing.JMenuItem();
        menuProcessos = new javax.swing.JMenu();
        submenuAgenda = new javax.swing.JMenuItem();
        submenuAtendimento = new javax.swing.JMenuItem();
        submenuProntuario = new javax.swing.JMenuItem();
        menuConfiguracoes = new javax.swing.JMenu();
        submenuPadraoDeAtendimento = new javax.swing.JMenuItem();
        submenuTipoDeAtendimento = new javax.swing.JMenuItem();
        submenuTipoDeProntuario = new javax.swing.JMenuItem();
        menuAdministrativo = new javax.swing.JMenu();
        submenuLogout = new javax.swing.JMenuItem();
        submenuGrupoDeUsuarios = new javax.swing.JMenuItem();
        submenuUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.controlLtHighlight);

        panelConteudo.setBackground(java.awt.SystemColor.controlLtHighlight);

        javax.swing.GroupLayout panelConteudoLayout = new javax.swing.GroupLayout(panelConteudo);
        panelConteudo.setLayout(panelConteudoLayout);
        panelConteudoLayout.setHorizontalGroup(
            panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1044, Short.MAX_VALUE)
        );
        panelConteudoLayout.setVerticalGroup(
            panelConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N

        submenuCadastros.setText("Cadastros");

        submenuAtendente.setText("Atendente");
        submenuAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuAtendenteActionPerformed(evt);
            }
        });
        submenuCadastros.add(submenuAtendente);

        submenuCertificacao.setText("Certificação");
        submenuCadastros.add(submenuCertificacao);

        submenuCliente.setText("Cliente");
        submenuCadastros.add(submenuCliente);

        submenuEspecializacao.setText("Especialização");
        submenuCadastros.add(submenuEspecializacao);

        submenuProfissional.setText("Profissional");
        submenuCadastros.add(submenuProfissional);

        menu.add(submenuCadastros);

        menuProcessos.setText("Processos");

        submenuAgenda.setText("Agenda");
        submenuAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuAgendaActionPerformed(evt);
            }
        });
        menuProcessos.add(submenuAgenda);

        submenuAtendimento.setText("Atendimento");
        menuProcessos.add(submenuAtendimento);

        submenuProntuario.setText("Prontuário");
        menuProcessos.add(submenuProntuario);

        menu.add(menuProcessos);

        menuConfiguracoes.setText("Configurações");

        submenuPadraoDeAtendimento.setText("Padrão de atendimento");
        menuConfiguracoes.add(submenuPadraoDeAtendimento);

        submenuTipoDeAtendimento.setText("Tipo de atendimento");
        menuConfiguracoes.add(submenuTipoDeAtendimento);

        submenuTipoDeProntuario.setText("Tipo de prontuário");
        menuConfiguracoes.add(submenuTipoDeProntuario);

        menu.add(menuConfiguracoes);

        menuAdministrativo.setText("Administrativo");

        submenuLogout.setText("Efetuar logout");
        submenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuLogoutActionPerformed(evt);
            }
        });
        menuAdministrativo.add(submenuLogout);

        submenuGrupoDeUsuarios.setText("Grupo de usuários");
        menuAdministrativo.add(submenuGrupoDeUsuarios);

        submenuUsuario.setText("Usuário");
        menuAdministrativo.add(submenuUsuario);

        menu.add(menuAdministrativo);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenuAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuAgendaActionPerformed
        /**
        OcorrenciaBusca ocorrenciaVisao = new OcorrenciaBusca();
        panelConteudo.removeAll();
        panelConteudo.add(ocorrenciaVisao);
        
        try 
        {
            ocorrenciaVisao.setMaximum(true);
        } 
        catch (PropertyVetoException ex) 
        {
            Logger.getLogger(Sistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ocorrenciaVisao.setVisible(true);
        */
    }//GEN-LAST:event_submenuAgendaActionPerformed

    private void submenuAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuAtendenteActionPerformed
        
        AtendenteBusca atendenteBusca = new AtendenteBusca(); 
        
        panelConteudo.removeAll();
        panelConteudo.add(atendenteBusca);
        
        try 
        {
            atendenteBusca.setMaximum(true);
        } 
        catch (PropertyVetoException ex) 
        {
            Logger.getLogger(SistemaVisao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        atendenteBusca.setVisible(true);
    }//GEN-LAST:event_submenuAtendenteActionPerformed

    private void submenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuLogoutActionPerformed
        /**
        int reply = JOptionPane.showConfirmDialog(null, "Você têm certeza que deseja sair do sistema?", "Atenção!", JOptionPane.YES_NO_OPTION);
            
        if ( reply == JOptionPane.YES_OPTION ) 
        {
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
            this.setVisible(false);
        }
        */
    }//GEN-LAST:event_submenuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaVisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaVisao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAdministrativo;
    private javax.swing.JMenu menuConfiguracoes;
    private javax.swing.JMenu menuProcessos;
    private javax.swing.JPanel panelConteudo;
    private javax.swing.JMenuItem submenuAgenda;
    private javax.swing.JMenuItem submenuAtendente;
    private javax.swing.JMenuItem submenuAtendimento;
    private javax.swing.JMenu submenuCadastros;
    private javax.swing.JMenuItem submenuCertificacao;
    private javax.swing.JMenuItem submenuCliente;
    private javax.swing.JMenuItem submenuEspecializacao;
    private javax.swing.JMenuItem submenuGrupoDeUsuarios;
    private javax.swing.JMenuItem submenuLogout;
    private javax.swing.JMenuItem submenuPadraoDeAtendimento;
    private javax.swing.JMenuItem submenuProfissional;
    private javax.swing.JMenuItem submenuProntuario;
    private javax.swing.JMenuItem submenuTipoDeAtendimento;
    private javax.swing.JMenuItem submenuTipoDeProntuario;
    private javax.swing.JMenuItem submenuUsuario;
    // End of variables declaration//GEN-END:variables
}
